import requests

body={
    "text":'''Edward, the eldest son of Edward III of England, Lord of Ireland and ruler of Gascony, and Queen Philippa, was born at Woodstock in the County of Oxfordshire, on 15 June 1330. His father, Edward III, had been at loggerheads with the French over English lands in France and also the kingship of France; Edward III's mother, Queen Isabella of France was a daughter of the French king Philip IV of France, thus placing her son in line for the throne of France. England and France's relations quickly deteriorated when the French king threatened to confiscate his lands in France, beginning the Hundred Years War. His mother was Queen Philippa of Hainault, daughter of the Count of Hainault, who married Edward III when his mother, Queen Isabella, arranged the marriage between them. His father on 10 September 1330 allowed five hundred marks a year from the profits of the county of Chester for his maintenance; on 25 February 1331, the whole of these profits were assigned to the queen for maintaining him and the king's sister Eleanor.[4] In July of that year, the king proposed to marry him to a daughter of Philip VI of France.[5]

His father was Edward III of England, who became king at the young age of fourteen years in 1327, when his father (and the Black Prince's grandfather) Edward II of England was deposed by his wife Isabella of France, daughter of Philip IV of France, and by the English nobility due to his ineffectiveness and weakness to assert his control over the government and his failed wars against Scotland. His mother, Philippa of Hainault, was the daughter of William II, Count of Hainault. The marriage between his mother and father was arranged by his grandmother, Isabella of France, to get financial and military aid from the Count of Hainault for her own benefit to depose her husband, Edward II. The marriage of Edward III and Phillippa of Hainault produced thirteen children; Edward was the eldest child and eldest son.

His father had begun a war with Scotland to regain lost territories which were captured by the Scots during the reign of Edward II and began the military operations undertaken by Edward III's grandfather, Edward I of England, recapturing English lands such as Berwick-Upon-Tweed. Edward III took his grandfather's military strategies and tactics against the Scots to avenge the humiliating defeat of the English under Edward II at the Battle of Bannockburn in 1314, and this time, Edward III defeated the Scots at the decisive Battle of Halidon Hill in 1333, killing many Scottish nobles and routing the entire Scottish army. Edward III was able to recover the country politically and militarily, and was welcomed as a "great champion of the English nation".

On 18 March 1333, Edward was invested with the earldom and county of Chester, and in the parliament of 9 February 1337, he was created Duke of Cornwall and received the duchy by charter dated 17 March. This is the earliest instance of the creation of a duke in England. By the terms of the charter the duchy was to be held by him and the eldest sons of kings of England.[6] His tutor was Dr. Walter Burley of Merton College, Oxford. His revenues were placed at the disposal of his mother in March 1334 for the expenses she incurred in bringing up him and his two sisters, Isabella and Joan.[7] Rumours of an impending French invasion led the king in August 1335 to order that he and his household should remove to Nottingham Castle as a place of safety.[8]

When two cardinals came to England at the end of 1337 to make peace between Edward III and Philip VI of France, the Duke of Cornwall is said to have met the cardinals outside the City of London and, in company with many nobles, to have conducted them to King Edward.[9] On 11 July 1338 his father, who was on the point of leaving England for Flanders, appointed him guardian of the kingdom during his absence, and he was appointed to the same office on 27 May 1340 and 6 October 1342;[10] he was, of course, too young to take any save a nominal part in the administration, which was carried on by the council. To attach Duke John III of Brabant to his cause, the king in 1339 proposed a marriage between the young Duke of Cornwall and John's daughter Margaret, and in the spring of 1345 wrote urgently to Pope Clement VI for a dispensation for the marriage.[11]

On 12 May 1343, Edward III created the duke Prince of Wales in a parliament held at Westminster, investing him with a circlet, gold ring, and silver rod. The prince accompanied his father to Sluys on 3 July 1345, and the king tried to persuade the burgomasters of Ghent, Bruges and Ypres to accept his son as their lord, but the murder of Jacob van Artevelde put an end to this project. Both in September and in the following April the prince was called on to furnish troops from his principality and earldom for the impending campaign in France, and as he incurred heavy debts in the king's service, his father authorised him to make his will and provided that, in case he fell in the war, his executors should have all his revenue for a year.[12]'''}

r=requests.post("http://localhost:8080/fact/",json=body)
print(r.text)